// ============================================================
// OrdenhaDigital — glossário para quem está começando
// Passar o mouse (ou tocar) sobre um termo mostra o que ele significa.
// Cobre: menu, indicadores, cabeçalhos de tabela, dados da ficha, títulos, campos de formulário,
// situações (etiquetas coloridas) e alertas. Dá para desligar tudo no botão "Explicações" da barra lateral.
// Para incluir um termo novo: acrescente em TERMOS (texto exato, minúsculo) ou em TERMOS_PADRAO (começo do texto).
// ============================================================

const TERMOS = {
  // ---------- menu ----------
  'painel': 'Resumo do dia: leite entregue, situação do rebanho e a lista do que precisa ser feito hoje.',
  'rebanho': 'Lista de todos os animais. Clicando num animal abre a ficha completa dele.',
  'fazendas': 'Cadastro das propriedades e o resumo do rebanho e do leite de cada uma.',
  'produção de leite': 'Leite do tanque de cada dia e a medição de leite de cada vaca (controle leiteiro).',
  'ranking de produção': 'Classificação das vacas que mais dão leite, com gráficos.',
  'reprodução': 'Inseminação, cobertura, exame de gestação, secagem e partos. O sistema avisa as datas.',
  'sanidade': 'Vacinas, exames, remédios dados às vacas e controle de mastite (inflamação do úbere).',
  'bezerras e novilhas': 'Cria (bezerros até a desmama) e recria (novilhas crescendo até a primeira cria).',
  'nutrição e estoque': 'O que cada lote come por dia, quanto custa e por quantos dias a ração ainda dura.',
  'qualidade e laticínio': 'Resultado mensal do laticínio (preço e análises do leite) e temperatura do tanque.',
  'financeiro': 'Receitas e despesas da atividade e o custo para produzir cada litro.',

  // ---------- categorias e conceitos do rebanho ----------
  'bezerra': 'Fêmea recém-nascida até a desmama (cerca de 2 meses) e um pouco depois, até uns 6 meses.',
  'bezerro': 'Macho recém-nascido até a desmama e um pouco depois.',
  'novilha': 'Fêmea jovem que ainda não pariu. Cresce até ter peso para a primeira inseminação (cerca de 330 kg).',
  'novilho': 'Macho jovem em crescimento, depois da fase de bezerro.',
  'touro': 'Macho reprodutor. Pode ser um touro do rebanho (monta natural) ou o touro de onde vem o sêmen da inseminação.',
  'lactação': 'Fase em que a vaca está dando leite, desde o parto até a secagem (cerca de 10 meses). "Em lactação" = vaca sendo ordenhada.',
  'seca': 'Vaca que parou de ser ordenhada para descansar antes do próximo parto. A secagem é feita cerca de 60 dias antes de parir.',
  'machos': 'Bezerros, novilhos e touros.',
  'lote': 'Grupo de animais que ficam juntos e comem a mesma dieta. Ex.: Lote 1 = vacas de alta produção.',
  'lotes': 'Grupos de animais que ficam juntos e comem a mesma dieta.',
  'brinco': 'Número de identificação do animal, preso na orelha.',
  'raça': 'Raça ou cruzamento do animal. Girolando é o cruzamento de Gir (zebu) com Holandês, muito usado no Brasil.',
  'registro': 'Número do animal na associação da raça. Comprova a genealogia (pais e avós) e valoriza o animal.',
  'categoria': 'Fase de vida do animal: bezerra, novilha, vaca em lactação, vaca seca ou macho. (No Financeiro: o tipo da receita ou despesa.)',
  'situação': 'Situação reprodutiva: se está prenhe, vazia (não prenhe), coberta aguardando exame, recém-parida etc.',
  'idade': 'Idade calculada pela data de nascimento.',
  'sexo': 'F = fêmea, M = macho.',
  'nascimento': 'Data em que o animal nasceu.',
  'lact.': 'Quantas vezes a vaca já pariu (número da lactação). 1 = primeira cria.',
  'lactações': 'Quantas vezes a vaca já pariu.',
  'l/dia': 'Litros de leite que a vaca deu no dia, pela última medição.',
  'procedência': 'De onde veio o animal: nascido na fazenda ou comprado (e de quem).',
  'fazenda': 'Propriedade onde o animal está.',
  'mãe': 'Vaca que pariu este animal.',
  'pai': 'Touro pai deste animal (da inseminação ou da monta).',
  'cria': 'Bezerro ou bezerra nascido.',
  'crias': 'Filhos e filhas desta vaca, com peso e se têm registro.',
  'genealogia': 'Árvore da família: pai, mãe e os quatro avós. Serve para evitar cruzar parentes e para o registro na associação.',
  'prêmios': 'Premiações em exposições ou torneios leiteiros.',
  'histórico': 'Tudo o que já aconteceu com o animal, do mais recente para o mais antigo.',
  'cobrições': 'Vezes em que a vaca foi inseminada ou coberta pelo touro.',
  'tratamentos': 'Remédios que o animal tomou.',
  'peso': 'Peso do animal na balança, com a evolução ao longo do tempo.',
  'identificação': 'Dados que identificam o animal: brinco, nome, registro, raça.',
  'situação atual': 'Para animal que já existia antes do sistema: informe como ele está hoje (lactações, último parto, se está prenhe). O sistema calcula o resto.',

  // ---------- ficha / reprodução ----------
  'último parto': 'Data em que a vaca pariu pela última vez. Dela o sistema conta os dias em lactação.',
  'produção': 'Litros por dia na última medição de leite.',
  'última cobrição': 'Data da última inseminação ou cobertura pelo touro. Dela sai a data prevista do parto (283 dias depois).',
  'coberturas desde o parto': 'Quantas vezes a vaca foi inseminada ou coberta depois do último parto. Vaca que emprenha fácil precisa de 1 ou 2. Com 3 ou mais, chame o veterinário.',
  'parto previsto': 'Data esperada do parto: 283 dias depois da cobrição que emprenhou a vaca.',
  'secar até': 'Data limite para parar de ordenhar a vaca (60 dias antes do parto), para ela descansar e produzir bem na próxima cria.',
  'pré-parto': 'Últimos 21 dias antes do parto. A vaca vai para um lote e dieta especiais para evitar doenças no parto.',
  'peso atual': 'Último peso registrado na balança.',
  'peso ao nascer': 'Peso da cria no dia em que nasceu.',
  'peso na desmama': 'Peso da cria quando parou de mamar.',
  'último peso': 'Peso da pesagem mais recente.',
  'ganho recente': 'Quanto o animal engordou por dia entre as duas últimas pesagens (em gramas por dia). Negativo = perdeu peso.',
  'ganho no período': 'Quanto o animal engordou por dia desde a primeira pesagem registrada.',
  'ganho': 'Quanto o animal engordou por dia desde a última pesagem (gramas por dia).',
  'ganho médio': 'Ganho de peso por dia das bezerras desde o nascimento. Meta: 600 g por dia ou mais.',

  // ---------- indicadores (quadros do topo) ----------
  'vacas em lactação': 'Vacas que estão sendo ordenhadas agora. O ideal é ter cerca de 83% das vacas em lactação e o resto secas.',
  'média por vaca': 'Litros por dia divididos pelo número de vacas em lactação.',
  'vacas prenhes': 'Porcentagem das vacas (em lactação + secas) que estão prenhes. Meta: 55% ou mais. Pouca vaca prenhe hoje = pouco leite daqui a meses.',
  'custo alimentar': 'Quanto custa a comida do rebanho para produzir cada litro de leite. É o maior custo da fazenda.',
  'custo alimentar por dia': 'Quanto o rebanho inteiro come por dia em reais, pelas dietas cadastradas.',
  'custo por litro': 'Quanto custa produzir cada litro de leite. Se for maior que o preço pago pelo laticínio, a fazenda está no prejuízo.',
  'média 7 dias': 'Média de litros entregues por dia na última semana. Tira o efeito de um dia bom ou ruim.',
  'descarte (carência)': 'Leite que não pode ir para o tanque porque a vaca está tomando remédio. Precisa ser jogado fora.',
  'del médio': 'Média de dias desde o parto das vacas em lactação. Entre 150 e 180 é o ideal: o rebanho está parindo com regularidade.',
  'campeã': 'A vaca em primeiro lugar no critério escolhido.',
  'média do grupo': 'Média das vacas que estão no ranking com os filtros escolhidos.',
  'top 10% produz': 'Quanto as 10% melhores vacas produzem a mais que a média. Mostra a diferença entre as melhores e o resto.',
  'diferença 1ª x última': 'Diferença entre a vaca que mais produz e a que menos produz.',
  'iep projetado': 'Intervalo Entre Partos previsto: tempo entre um parto e o próximo. Meta de 13 meses (uma cria por ano, mais ou menos).',
  'parto até concepção': 'Quantos dias, em média, a vaca leva depois do parto para emprenhar de novo. Meta: até 110 dias.',
  'doses por prenhez': 'Quantas inseminações, em média, foram precisas para cada vaca emprenhar. Quanto menor, melhor (menos sêmen gasto).',
  'vazias com del acima de 150': 'Vacas não prenhes com mais de 150 dias de paridas. Estão demorando para emprenhar.',
  'em tratamento': 'Animais tomando remédio ou ainda no prazo de carência.',
  'leite descartado': 'Litros por dia jogados fora por causa da carência dos remédios.',
  'ccs acima de 500 mil': 'Vacas com sinal de mastite (inflamação do úbere) pela análise de laboratório.',
  'bezerreiro': 'Local e grupo das crias até a desmama.',
  'em aleitamento': 'Crias que ainda recebem leite.',
  'novilhas': 'Fêmeas jovens que ainda não pariram.',
  'insumos em alerta': 'Alimentos com menos de 15 dias de estoque. Hora de comprar.',
  'valor em estoque': 'Quanto vale, em reais, tudo o que está no estoque de alimentos.',
  'gordura / proteína': 'Teor de gordura e de proteína do leite. Quanto maior, mais o laticínio costuma pagar.',
  'área total': 'Tamanho total da propriedade em hectares (1 ha = 10.000 m², cerca de um campo e meio de futebol).',
  'animais': 'Quantidade de animais ativos.',
  'leite por dia': 'Litros por dia somando a última medição de cada vaca.',
  'em lactação': 'Vacas sendo ordenhadas.',

  // ---------- títulos de seções ----------
  'atenção hoje': 'Tudo o que precisa ser feito ou olhado hoje. Clique numa linha para ir à tela certa.',
  'composição do rebanho': 'Quantos animais há em cada fase (lactação, secas, novilhas, bezerras, machos).',
  'próximos partos': 'Vacas prenhes mais perto de parir.',
  'produção por lote': 'Quanto leite cada lote está dando, pela última medição de cada vaca.',
  'últimas entregas': 'Últimos lançamentos de leite do tanque. Clique para corrigir.',
  'controle leiteiro individual': 'Última medição de leite de cada vaca (manhã, tarde e total).',
  'menores produções': 'Vacas que menos produzem: candidatas a secar ou a sair do rebanho.',
  'diagnóstico de gestação': 'Vacas cobertas há 28 dias ou mais: já dá para o veterinário confirmar se estão prenhes (ultrassom ou toque).',
  'observar retorno de cio': 'Vacas cobertas há 18 a 24 dias. Se mostrarem cio de novo, não emprenharam e devem ser inseminadas outra vez.',
  'liberadas para inseminar': 'Vacas vazias que já passaram de 45 dias do parto (ou novilhas no peso). Inseminar no próximo cio.',
  'secar': 'Vacas prenhes que estão a 60 dias ou menos do parto: precisam parar de ser ordenhadas.',
  'partos previstos': 'Vacas que vão parir nos próximos 30 dias. Acompanhar e levar para o pré-parto.',
  'problema reprodutivo': 'Vacas que não emprenham há muito tempo. Levar ao veterinário.',
  'botijão de sêmen': 'Estoque de doses de sêmen (congeladas em nitrogênio) para a inseminação, por touro.',
  'eventos recentes': 'Últimos acontecimentos reprodutivos registrados.',
  'calendário sanitário': 'Vacinas e manejos que se repetem, com a próxima data calculada.',
  'tratamentos ativos': 'Animais tomando remédio agora ou ainda em carência.',
  'ccs individual alta': 'Vacas com CCS acima de 500 mil: provável mastite. Fazer o teste da raquete (CMT) e falar com o veterinário.',
  'dietas por lote': 'O que cada animal de cada lote come por dia, em kg, e quanto custa.',
  'estoque de insumos': 'Quanto tem de cada alimento e por quantos dias ainda dura.',
  'movimentações recentes': 'Entradas (compras), saídas e ajustes do estoque.',
  'análises e pagamento por mês': 'Resultado que o laticínio manda todo mês: qualidade do leite e preço pago.',
  'temperatura do tanque': 'O leite precisa ser resfriado a 4 °C em até 3 horas depois da ordenha, senão as bactérias crescem.',
  'resultado por categoria': 'Receitas e despesas de cada tipo, mês a mês.',
  'curva de lactação atual': 'Quanto a vaca deu de leite em cada medição desde o parto. O normal é subir até uns 50 dias e depois cair devagar. A linha tracejada é o esperado.',
  'curvas de lactação das 5 melhores': 'Produção das 5 melhores vacas ao longo dos dias depois do parto.',
  'distribuição do rebanho': 'Quantas vacas há em cada faixa de produção.',
  'média por raça': 'Produção média de cada raça do rebanho.',
  'média por ordem de lactação': 'Produção média por número de crias. Vacas de 1ª cria costumam produzir menos que as de 3ª ou 4ª.',
  'classificação completa': 'Todas as vacas em ordem, com todos os números de produção.',
  'nota fiscal': 'Dados da nota fiscal da compra ou venda.',
  'animais sem fazenda': 'Animais que ainda não têm fazenda escolhida no cadastro.',

  // ---------- cabeçalhos de tabela ----------
  // ---------- alertas do painel ----------
  'leite em carência — descartar': 'Vacas tomando remédio: o leite delas deve ser ordenhado separado e jogado fora até a data de liberação.',
  'vacina ou manejo atrasado': 'Vacina ou cuidado do calendário que passou da data. Veja em Sanidade.',
  'vacina ou manejo vencendo': 'Vacina ou cuidado que vence nos próximos 15 dias.',
  'partos previstos em 30 dias': 'Vacas que vão parir no próximo mês. Acompanhar e levar para o lote de pré-parto.',
  'vacas para secar (parto em até 60 dias)': 'Vacas prenhes perto do parto: parar de ordenhar para elas descansarem.',
  'diagnóstico de gestação a fazer': 'Vacas cobertas há 28 dias ou mais: pedir ao veterinário para confirmar a prenhez.',
  'liberadas para inseminar': 'Vacas e novilhas prontas para inseminar no próximo cio.',
  'ccs individual acima de 500 mil': 'Vacas com sinal de mastite pela análise de laboratório.',
  'bezerreiro: desmama ou vacina b19': 'Crias que já passaram de 60 dias (desmamar) ou bezerras na idade da vacina contra brucelose.',
  'insumo com menos de 15 dias de estoque': 'Alimento acabando: comprar.',
  'vazias com mais de 150 dias em lactação': 'Vacas que não emprenham há muito tempo depois do parto. Levar ao veterinário.',

  // ---------- legendas e outros ----------
  'diário': 'Linha com o valor de cada dia.',
  'pesagens (l/dia)': 'Pontos com cada medição de leite da vaca desde o parto.',
  'curva esperada': 'Quanto uma vaca como esta costuma produzir em cada fase da lactação.',
  'eixo: dias em lactação': 'Na linha de baixo do gráfico: dias desde o parto.',
  'receitas': 'Dinheiro que entrou.', 'despesas': 'Dinheiro que saiu.',
  '1º': 'Primeiro lugar (ouro).', '2º': 'Segundo lugar (prata).', '3º': 'Terceiro lugar (bronze).',
  'secas': 'Vacas secas (sem ordenhar, esperando o parto).',
  'nasc.': 'Data de nascimento.', 'obs.': 'Observação.',
  'por dia': 'Quanto o rebanho come por dia deste alimento.', 'baixa': 'Quanto será descontado do estoque.',
  'kg/cab/dia': 'Quilos deste alimento que cada animal do lote come por dia.',
  'doença': 'Problema tratado.',
  'ok': 'Tudo certo.',
  'não recebeu': 'A cria não mamou o colostro nas primeiras horas: fica sem defesas e precisa de atenção.',
  'manutenção': 'Consertos e peças (ordenhadeira, tanque, cercas, máquinas).',
  'venda de animais': 'Dinheiro da venda de bezerros, vacas de descarte e outros animais.',
  'venda de leite': 'Pagamento do laticínio pelo leite.',
  'energia': 'Conta de luz (ordenhadeira, tanque de resfriamento, bomba de água).',
  'alimentação': 'Ração, silagem, sal mineral e outros alimentos.',
  'mão de obra': 'Salários e encargos dos funcionários.',
  'combustível': 'Diesel e gasolina.',
  'impostos e taxas': 'Impostos, taxas e contribuições.',
  'arrendamento': 'Aluguel de terra.',
  'outras despesas': 'Gastos que não se encaixam nas outras categorias.',
  'outras receitas': 'Entradas de dinheiro que não são leite nem venda de animais.',
  'manhã (l)': 'Litros da ordenha da manhã desta vaca.', 'tarde (l)': 'Litros da ordenha da tarde desta vaca.',
  'nome': 'Nome do animal, se tiver (ou nome do lote / insumo).',

  'mãe na desmama': 'Peso da vaca quando esta cria desmamou. Mostra se a vaca perdeu muito peso amamentando.',
  'desmama': 'Peso da cria quando parou de mamar.',
  'ao nascer': 'Peso da cria no nascimento.',
  'leite/dia': 'Litros de leite que a cria recebe por dia.',
  'colostro': 'Primeiro leite da vaca, rico em defesas. A cria precisa mamar nas primeiras 6 horas de vida, senão adoece com facilidade.',
  'peso-alvo': 'Quanto falta para a novilha chegar a 330 kg, o peso para a primeira inseminação.',
  'pesagem': 'Data da última medição de leite da vaca.',
  'manhã': 'Litros da ordenha da manhã.',
  'tarde': 'Litros da ordenha da tarde.',
  'total l': 'Litros no dia (manhã + tarde).',
  'vacas': 'Quantidade de vacas.',
  'média l': 'Média de litros por vaca.',
  'litros': 'Litros entregues ao laticínio no dia.',
  'descarte': 'Litros jogados fora no dia por causa de remédio (carência).',
  'doses': 'Doses de sêmen no botijão.',
  'r$/dose': 'Preço de cada dose de sêmen.',
  'cabeças': 'Número de animais.',
  'dieta': 'Alimentos e quantidades (kg por animal por dia).',
  'r$/cab/dia': 'Custo da comida de um animal por dia.',
  'r$/lote/dia': 'Custo da comida do lote inteiro por dia.',
  'r$/litro': 'Custo da comida do lote para cada litro de leite produzido.',
  'insumo': 'Alimento ou produto do estoque (silagem, ração, sal mineral...).',
  'estoque': 'Quantidade disponível.',
  'quantidade': 'Quanto entrou ou saiu do estoque.',
  'consumo/dia': 'Quanto o rebanho come por dia deste alimento, pelas dietas.',
  'dias': 'Por quantos dias o estoque ainda dura no ritmo atual.',
  'cobertura': 'Barra de quanto tempo o estoque cobre (verde = tranquilo, amarelo = menos de 30 dias, vermelho = menos de 15).',
  'preço': 'Preço por unidade.',
  'mês': 'Mês de referência.',
  'volume l': 'Litros entregues ao laticínio no mês.',
  'gord. %': 'Porcentagem de gordura do leite.',
  'prot. %': 'Porcentagem de proteína do leite.',
  'preço base': 'Preço por litro antes dos prêmios e descontos por qualidade.',
  'bonificação': 'Valor a mais (ou a menos) por litro que o laticínio paga pela qualidade e pelo volume do leite.',
  'preço final': 'Preço base + bonificação: quanto o laticínio pagou por litro.',
  'valor bruto': 'Volume × preço final: quanto o laticínio pagou no mês.',
  '°c': 'Temperatura do leite no tanque em graus.',
  'hora': 'Hora da leitura.',
  'última variação': 'Quanto a produção da vaca subiu (▲) ou caiu (▼) em relação à medição anterior.',
  'média 90 d': 'Média de litros por dia nos últimos 90 dias.',
  'total lactação': 'Litros produzidos desde o parto.',
  'proj. 305 d': 'Quanto a vaca deve produzir numa lactação padrão de 305 dias (10 meses), pela curva dela.',
  'atual l/dia': 'Litros por dia na última medição.',
  '#': 'Posição no ranking.',
  'vacina / manejo': 'Vacina, exame ou cuidado que se repete de tempos em tempos.',
  'grupo': 'Quais animais recebem.',
  'última': 'Data da última aplicação.',
  'próxima': 'Data da próxima aplicação, calculada pela frequência.',
  'frequência': 'De quanto em quanto tempo precisa repetir.',
  'doença / medicamento': 'Doença tratada e remédio usado.',
  'libera': 'Data em que o leite da vaca volta a poder ir para o tanque.',
  'início': 'Data em que começou.',
  'carência': 'Dias depois do fim do remédio em que o leite (ou a carne) não pode ser vendido, porque ainda tem resíduo do remédio.',
  'descrição': 'Detalhe do lançamento.',
  'fornecedor / cliente': 'De quem comprou (despesa) ou para quem vendeu (receita).',
  'valor': 'Valor em reais.',
  'data': 'Data do acontecimento.',
  'vaca': 'Vaca.',
  'animal': 'Animal.',
  'evento': 'O que aconteceu (inseminação, parto, secagem...).',
  'peso novo (kg)': 'Peso de hoje na balança.',

  // ---------- campos de formulário ----------
  'nº de registro (associação)': 'Número que a associação da raça dá ao animal registrado. Deixe em branco se não tiver.',
  'peso atual (kg)': 'Peso na balança hoje. Depois do cadastro, os pesos novos são lançados no botão Pesar.',
  'peso ao nascer (kg)': 'Peso da cria no dia do nascimento.',
  'observação': 'Qualquer anotação livre.',
  'pai (touro)': 'Nome ou código do touro pai.',
  'registro do pai': 'Número de registro do touro pai na associação.',
  'avô paterno': 'Pai do pai.', 'avó paterna': 'Mãe do pai.',
  'avô materno': 'Pai da mãe.', 'avó materna': 'Mãe da mãe.',
  'mãe (se estiver no rebanho)': 'Escolha a mãe se ela estiver cadastrada. Se não estiver, deixe em branco e digite o nome dela no campo de baixo.',
  'mãe (nome, se de fora)': 'Nome da mãe quando ela não é do rebanho (animal comprado, por exemplo).',
  'registro da mãe': 'Número de registro da mãe na associação.',
  'nº de lactações': 'Quantas vezes a vaca já pariu.',
  'data do último parto': 'Quando a vaca pariu pela última vez.',
  'situação reprodutiva': 'Como a vaca está: pós-parto (pariu há pouco), vazia (não prenhe), coberta (inseminada, sem exame ainda), prenhe (exame confirmou) ou, na novilha, em recria / apta para inseminar.',
  'data da última cobrição': 'Quando foi a última inseminação ou cobertura pelo touro.',
  'touro da última cobrição': 'Qual touro (ou sêmen) foi usado.',
  'data da secagem': 'Quando a vaca parou de ser ordenhada.',
  'sêmen do botijão': 'Escolha o touro. Uma dose sai do estoque do botijão automaticamente.',
  'ou outro sêmen': 'Se usou sêmen que não está cadastrado no botijão, digite o touro aqui.',
  'touro da monta': 'Touro que cobriu a vaca naturalmente.',
  'fim do período com o touro': 'Se o touro ficou uns dias junto com a vaca, a data em que foi separado.',
  'início (touro entrou)': 'Dia em que o touro foi colocado com a vaca.',
  'touro (pai do embrião)': 'Touro pai do embrião transferido.',
  'doadora (mãe do embrião)': 'Vaca de alta genética de onde veio o embrião. A vaca que recebe (a receptora) só gera o bezerro.',
  'idade da gestação (dias)': 'Quantos dias de prenhez o veterinário viu no ultrassom. Com isso o sistema acerta a data do parto.',
  'brinco da cria': 'Número do brinco colocado na cria.', 'brinco da bezerra': 'Número do brinco colocado na bezerra.',
  'brinco do bezerro (opcional)': 'Se o bezerro macho vai ficar na fazenda, informe o brinco para cadastrá-lo. Se vai ser vendido logo, pode deixar em branco.',
  'nome da cria': 'Nome da cria, se quiser dar.',
  'registro da cria': 'Número de registro da cria, se já tiver.',
  'recebeu colostro nas primeiras 6 horas': 'A cria mamou o primeiro leite da mãe (colostro) logo depois de nascer. Sem isso ela fica sem defesas e adoece fácil.',
  'ordenha da manhã (l)': 'Litros que a vaca deu na ordenha da manhã.',
  'ordenha da tarde (l)': 'Litros que a vaca deu na ordenha da tarde. Se a fazenda ordenha só uma vez, deixe 0.',
  'ccs (mil cél/ml)': 'Resultado da CCS do laboratório para esta vaca. Deixe em branco se não mandou amostra.',
  'cbt (mil ufc/ml)': 'Resultado da CBT (bactérias no leite) que vem no relatório do laticínio.',
  'doença / motivo': 'Qual problema o animal tem.',
  'medicamento': 'Nome do remédio aplicado.',
  'dias de aplicação': 'Por quantos dias o remédio é dado.',
  'carência do leite (dias)': 'Está na bula do remédio. Dias depois da última aplicação em que o leite não pode ir para o tanque.',
  'carência da carne (dias)': 'Está na bula. Dias em que o animal não pode ser vendido para abate.',
  'motivo': 'Por que o animal saiu do rebanho.',
  'valor recebido (r$)': 'Quanto recebeu na venda. Entra no Financeiro sozinho.',
  'exposição / torneio': 'Nome do evento em que o animal foi premiado.',
  'colocação / título': 'Que prêmio ganhou (campeã, 1º lugar...).',
  'peso (kg)': 'Peso na balança.',
  'leite por dia (l)': 'Quantos litros de leite a cria está recebendo por dia.',
  'liberar para inseminação (apta p/ ia)': 'Marque quando a novilha atingir o peso (cerca de 330 kg). Ela passa a aparecer na lista de liberadas para inseminar.',
  'data da pesagem': 'Dia em que os animais foram pesados.',
  'data do controle': 'Dia em que o leite das vacas foi medido.',
  'litros entregues': 'Total que foi para o tanque no dia (o que o laticínio coletou).',
  'litros descartados': 'Leite jogado fora no dia (vacas em carência de remédio).',
  'mês de referência': 'Mês a que se refere o resultado do laticínio.',
  'volume entregue (l)': 'Litros que o laticínio recebeu no mês (está no extrato dele).',
  'preço base (r$/l)': 'Preço por litro antes dos prêmios e descontos (está no extrato do laticínio).',
  'bonificação (r$/l, negativo se desconto)': 'Prêmio por litro que o laticínio pagou pela qualidade. Se ele descontou, digite com sinal de menos.',
  'gordura (%)': 'Porcentagem de gordura do leite no mês.',
  'proteína (%)': 'Porcentagem de proteína do leite no mês.',
  'temperatura (°c)': 'Temperatura mostrada no termômetro do tanque.',
  'tipo': 'Receita (entrada de dinheiro) ou despesa (saída). No lote: para que serve o lote.',
  'valor (r$)': 'Valor em reais.',
  'nº da nota': 'Número impresso na nota fiscal.',
  'fornecedor': 'Empresa ou pessoa de quem comprou.',
  'cliente': 'Para quem vendeu.',
  'arquivo da nota (pdf ou foto)': 'Anexe o PDF ou uma foto da nota. Fica guardada com segurança para consultar depois.',
  'nome da fazenda': 'Nome da propriedade.',
  'car (cadastro ambiental rural)': 'Registro obrigatório do imóvel rural no órgão ambiental. O número está no recibo do CAR.',
  'uf': 'Estado onde fica a propriedade.',
  'proprietário': 'Dono da propriedade.',
  'município': 'Cidade onde fica a propriedade.',
  'inscrição estadual': 'Número do produtor rural na Secretaria da Fazenda do estado (usado nas notas fiscais).',
  'área total (ha)': 'Tamanho total da propriedade em hectares.',
  'área de pastagem (ha)': 'Parte da área com capim para o gado. Serve para calcular quantas cabeças cabem por hectare.',
  'pastagem': 'Área com capim para o gado, em hectares.',
  'fazenda ativa': 'Desmarque para esconder uma fazenda que não é mais usada, sem apagar os dados.',
  'código / nome': 'Nome ou código do touro no catálogo da central de sêmen.',
  'central': 'Empresa que vende o sêmen.',
  'preço por dose (r$)': 'Quanto custou cada dose de sêmen.',
  'doses iniciais': 'Quantas doses deste touro já estão no botijão.',
  'doses no botijão': 'Quantas doses restam.',
  'sêmen sexado (fêmea)': 'Sêmen selecionado para nascer quase sempre fêmea. É mais caro, mas garante bezerras para o rebanho.',
  'quantidade de doses': 'Quantas doses chegaram.',
  'data da compra': 'Quando comprou.',
  'unidade': 'Como o insumo é medido (kg, tonelada, saco, litro). Para dieta, use kg.',
  'preço por unidade (r$)': 'Quanto custa cada kg (ou unidade) do insumo.',
  'estoque inicial': 'Quanto já tem guardado hoje.',
  'estoque atual (ajuste)': 'Corrige o estoque para o que tem de verdade (depois de contar ou pesar).',
  'fornecedor / nf': 'De quem comprou e o número da nota.',
  'quantos dias': 'Quantos dias de consumo descontar do estoque de uma vez.',
  'repetir a cada (dias)': 'De quanto em quanto tempo este manejo precisa ser refeito. Ex.: 180 = de 6 em 6 meses.',
  'ordem': 'Posição do lote na lista. Nos lotes de lactação: 1 = alta produção, 2 = média, 3 = fim de lactação.',
  'produto / lote': 'Nome da vacina ou do produto e o lote de fabricação (está na embalagem).',
  'custo total (r$)': 'Quanto gastou nesta aplicação. Entra no Financeiro.',
  'peso da cria na desmama (kg)': 'Peso da cria no dia em que parou de mamar.',
  'veterinário / atestado': 'Nome do veterinário que aplicou ou o número do atestado de vacinação.',
};

// Termos que mudam no fim (datas, números) — comparados pelo começo do texto
const TERMOS_PADRAO = [
  [/^lançar a (compra|receita)/, 'Marcado, o sistema já lança o valor no Financeiro sozinho, sem precisar digitar de novo.'],
  [/^\d{2}\/\d{2}$/, 'Data em que o leite desta vaca volta a poder ir para o tanque.'],
  [/^\d+$/, 'Verde = dentro do limite da norma do leite. Vermelho = acima do limite (o laticínio pode descontar).'],
  [/^\d+ prêmios?$/, 'Quantidade de prêmios deste animal. Veja a lista mais abaixo na ficha.'],
  [/^\d+ pendente\(s\)$/, 'Bezerras na idade da vacina B19 que ainda não foram vacinadas. Veja em Bezerras e novilhas.'],
  [/^histórico de tratamentos/, 'Remédios dados aos animais nos últimos 90 dias.'],
  [/^prenhe · parto/, 'Vaca prenhe (confirmado no exame). A data é o parto previsto: 283 dias depois da cobrição.'],
  [/^coberta há \d+ d/, 'Foi inseminada ou coberta e ainda não fez o exame de gestação. Com 28 dias ou mais já dá para o veterinário confirmar.'],
  [/^seca · parto/, 'Vaca seca: parou de ser ordenhada para descansar antes do parto. A data é o parto previsto.'],
  [/^seca · vazia/, 'Vaca seca que não está prenhe. Precisa de avaliação: não vai gerar bezerro nem leite.'],
  [/^vazia · del alto/, 'Não está prenhe e já tem mais de 150 dias de parida. Está demorando para emprenhar: chamar o veterinário.'],
  [/^(vazia · )?liberada p\/ ia$/, 'Não está prenhe e já passou dos 45 dias de descanso depois do parto. Inseminar no próximo cio.'],
  [/^vazia$/, 'Não está prenhe.'],
  [/^pós-parto$/, 'Pariu há menos de 45 dias. É o descanso do útero antes de inseminar de novo (espera voluntária).'],
  [/^apta p\/ ia$/, 'Novilha com idade e peso (cerca de 330 kg) para a primeira inseminação.'],
  [/^em recria$/, 'Animal jovem crescendo, ainda sem idade ou peso para reproduzir.'],
  [/^aleitamento/, 'Cria que ainda mama (recebe leite). A desmama costuma ser aos 60 dias.'],
  [/^desmamad[ao]/, 'Cria que já parou de receber leite e come ração e capim.'],
  [/^reprodutor$/, 'Touro usado para cobrir as vacas (monta natural).'],
  [/^recria$/, 'Macho jovem crescendo, depois da desmama.'],
  [/^(leite em )?carência$|^descartar leite$/, 'A vaca tomou remédio e o leite dela não pode ir para o tanque até a data de liberação. Ordenhar separado e jogar fora.'],
  [/^registrad[oa]$/, 'Animal com número de registro na associação da raça (genealogia comprovada).'],
  [/^sem registro$/, 'Sem registro na associação da raça. (No calendário sanitário: ainda não há nenhuma aplicação lançada.)'],
  [/^repor$/, 'Só restam 3 doses ou menos deste touro no botijão. Hora de comprar.'],
  [/^atrasad[ao]( \d+ d)?$/, 'Passou da data. Na sanidade: vacina ou manejo vencido. Na reprodução: já deveria ter sido feito.'],
  [/^em dia$/, 'Dentro do prazo.'],
  [/^vence hoje$|^vence em \d+ d$/, 'Vence em até 15 dias: programe a aplicação.'],
  [/^vacinar$/, 'Bezerra na idade da vacina B19 (entre 3 e 8 meses). Chamar o veterinário.'],
  [/^fora da idade$/, 'Passou dos 8 meses sem a vacina B19. Falar com o veterinário sobre como regularizar.'],
  [/^aos 3 meses$/, 'Ainda é nova para a vacina B19, que é dada entre 3 e 8 meses.'],
  [/^vacinada/, 'Já recebeu a vacina B19 contra brucelose.'],
  [/^desmamar$/, 'Já passou dos 60 dias: hora de parar de dar leite para a cria.'],
  [/^comprar$/, 'Menos de 15 dias de estoque.'],
  [/^acima de 4 °c$/, 'Leite quente demais no tanque: risco de bactérias (CBT alta). Verificar o resfriador.'],
  [/^sexado$/, 'Sêmen selecionado para nascer quase sempre fêmea.'],
  [/^libera \d/, 'Data em que o leite desta vaca volta a poder ir para o tanque.'],
  [/^sem carência$/, 'O remédio não exige descartar o leite.'],
  [/^concluído$/, 'Tratamento terminado e carência já passou.'],
  [/^entrada$/, 'Compra ou chegada no estoque.'],
  [/^saída$/, 'Retirada do estoque.'],
  [/^ajuste$/, 'Correção do estoque para o valor real contado.'],
  [/^macho$/, 'Animal macho.'], [/^fêmea$/, 'Animal fêmea.'],
  [/^em \d+ dias$/, 'Faltam estes dias para o parto previsto.'],
  [/^atrasado \d+ d$/, 'Já passou da data prevista do parto. Acompanhar a vaca de perto.'],
  [/^leite entregue/, 'Litros que foram para o tanque (coletados pelo laticínio) no último dia lançado. O ▲▼ compara com a média da semana.'],
  [/^entregue ·/, 'Litros que foram para o tanque no último dia lançado.'],
  [/^preço final/, 'Quanto o laticínio pagou por litro no mês: preço base + bonificação.'],
  [/^receitas ·/, 'Dinheiro que entrou no mês (leite, venda de animais...).'],
  [/^despesas ·/, 'Dinheiro que saiu no mês (ração, funcionários, remédios, energia...).'],
  [/^resultado ·/, 'Receitas menos despesas. Positivo = lucro, negativo = prejuízo.'],
  [/^mastite clínica/, 'Casos de mastite com sinais visíveis (leite com grumos, úbere inchado ou quente) nos últimos 90 dias.'],
  [/^leite no tanque/, 'Litros entregues ao laticínio por dia. A linha pontilhada é a média de 7 dias.'],
  [/^(top \d+|todas as vacas) ·/, 'As vacas em ordem de produção. As 3 primeiras em ouro, prata e bronze; a linha pontilhada é a média.'],
  [/^crias \(\d+\)$/, 'Filhos e filhas desta vaca, com peso e se têm registro.'],
  [/^lançamentos de/, 'Todas as receitas e despesas lançadas no mês. Clique para editar.'],
  [/^receitas x despesas/, 'Comparação do que entrou e do que saiu de dinheiro nos últimos 6 meses.'],
  [/^quantidade \(/, 'Quanto entrou ou saiu do estoque.'],
  [/^preço por .+ \(r\$\)$/, 'Preço pago por unidade nesta compra. Atualiza o preço do insumo.'],
  [/^peso da mãe/, 'Peso da vaca no dia em que a cria desmamou. Mostra quanto ela perdeu amamentando.'],
  [/^peso atual$/, 'Último peso registrado. Para lançar um peso novo, use o botão Pesar na ficha.'],
];

const _alvosTermo = '.nav a, .kpi .lbl, .tbl th, .dl dt, .card > header h2, .sec-t, .pill, .alert b, .form label, .legend span, .gen-box small';
function _normTermo(t) { return t.replace(/\s+/g, ' ').trim().replace(/([a-zà-ÿ)])\s*\d+$/i, '$1').toLowerCase(); }
function buscarTermo(txt) {
  const n = _normTermo(txt); if (!n) return null;
  return TERMOS[n] || (TERMOS_PADRAO.find(([re]) => re.test(n)) || [])[1] || null;
}
function marcarTermos(raiz) {
  if (!raiz || !explicacoesLigadas()) return;
  raiz.querySelectorAll(_alvosTermo).forEach(el => {
    if (el.dataset.termoOk) return; el.dataset.termoOk = '1';
    if (el.matches('.form label')) {
      // no campo de formulário a explicação fica só no texto do rótulo, não na caixa de digitar
      const caixa = n => n.nodeType === 1 && ['INPUT', 'SELECT', 'TEXTAREA', 'DATALIST'].includes(n.tagName);
      const filhos = [...el.childNodes], iCaixa = filhos.findIndex(caixa);
      // caixa de marcar vem antes do texto; campo comum vem depois
      const nos = iCaixa === 0 ? filhos.slice(1).filter(n => !caixa(n)) : filhos.slice(0, iCaixa < 0 ? filhos.length : iCaixa);
      const texto = nos.map(n => n.textContent).join('').trim(), tip = buscarTermo(texto);
      if (!tip || !nos.length) return;
      const sp = document.createElement('span'); sp.className = 'termo'; sp.dataset.tip = tip;
      nos[0].before(sp); nos.forEach(n => sp.appendChild(n));
      return;
    }
    const tip = buscarTermo(el.textContent); if (!tip) return;
    el.classList.add('termo'); el.dataset.tip = tip;
  });
}
document.addEventListener('mouseover', e => {
  if (!explicacoesLigadas() || !e.target.closest) return;
  if (e.target.closest('abbr.sig')) return;                     // sigla tem prioridade
  const t = e.target.closest('.termo'); if (!t) return;
  mostrarTermo(t);
});
document.addEventListener('mouseout', e => { if (e.target.closest && e.target.closest('.termo') && !(e.relatedTarget && e.target.closest('.termo').contains(e.relatedTarget))) esconderSigla(); });
document.addEventListener('click', e => { const t = e.target.closest && e.target.closest('.termo'); if (t && explicacoesLigadas() && !t.closest('a, button')) mostrarTermo(t); });
function mostrarTermo(t) {
  const rot = (t.closest('.form label') ? t.textContent : t.textContent).replace(/\s+/g, ' ').trim();
  mostrarDica(t, t.dataset.tip, rot.length <= 40 ? rot : '');
}
let _pendTermo = false;
new MutationObserver(() => {
  if (_pendTermo) return; _pendTermo = true;
  setTimeout(() => { _pendTermo = false; marcarTermos(document.getElementById('main')); marcarTermos(document.getElementById('layer')); marcarTermos(document.querySelector('.side')); }, 30);
}).observe(document.documentElement, { childList: true, subtree: true });
